Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CbsStudents.Data;
using cbsStudents.Models.Entities;

namespace cbsStudents.Controllers
{
    [Authorize]
    public class EventController : Controller
    {
        private readonly CbsStudentsContext _context;

        private readonly UserManager<IdentityUser> _userManager;

        private readonly RoleManager<IdentityRole> _roleManager;

        public EventController(RoleManager<IdentityRole> roleManager,CbsStudentsContext context, UserManager<IdentityUser> userManager)
        {
            this._roleManager = roleManager;
            this._userManager = userManager;
            this._context = context;

        }

        [AllowAnonymous]
        // GET: Event
        public IActionResult Index(string SearchString = "")
        {
            if(SearchString == null)
        {
            SearchString = "";
        }
        var events = from e in _context.Event select e;
        events = events.Where(x => x.EventName.Contains(SearchString)).Include(y => y.User);
        
        ViewBag.SearchString = SearchString;
        var vm = new EventIndexVm{Events = events.ToList(), SearchString = SearchString};
        
        return View(vm);
        }

        [AllowAnonymous]
        // GET: Event/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event.Include(x => x.User).Include(x => x.Comments).ThenInclude(x => x.User).FirstOrDefaultAsync(x => x.EventId == id);

            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Event/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Event/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventId,EventName,Text,Location,Date,Status")] Event @event)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);
                @event.UserId = user.Id;
                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // GET: Event/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var @event = await _context.Event.Include(x => x.User).Include(x => x.Comments).ThenInclude(x => x.User).FirstOrDefaultAsync(x => x.EventId == id);

            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }

        // POST: Event/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventId,EventName,Text,Location,Date,Status,UserId")] Event @event)
        {
            if (id != @event.EventId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.EventId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // GET: Event/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Event/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);
            
            var @event = await _context.Event.FindAsync(id);
            if(user == @event.User || User.IsInRole("Admin")){
                _context.Event.Remove(@event);
                await _context.SaveChangesAsync();
            } else {
                return Problem("You idiot");
            }
            
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
            return _context.Event.Any(e => e.EventId == id);
        }
    }
}

Controllers/PostsController.cs
using Microsoft.AspNetCore.Mvc;
using cbsStudents.Models.Entities;
using CbsStudents.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace cbsStudents.Controllers;

[Authorize]
public class PostsController : Controller
{
    private CbsStudentsContext _context;
    private readonly UserManager<IdentityUser> _userManager;
    
    public PostsController(CbsStudentsContext context, UserManager<IdentityUser> userManager){
        this._userManager = userManager;
        this._context = context;
    }
    
    
    [AllowAnonymous]
    public IActionResult Index(string SearchString = "")
    {
        if(SearchString == null)
        {
            SearchString = "";
        }
        var posts = from p in _context.Posts select p;
        posts = posts.Where(x => x.Title.Contains(SearchString)).Include(y => y.User);
        posts = posts.OrderBy(x => x.Created);
        
        ViewBag.SearchString = SearchString;
        var vm = new PostIndexVm{Posts = posts.ToList(), SearchString = SearchString};
        
        return View(vm);
    }
    public IActionResult Test()
    {
        var vm = from p in _context.Posts select new MyTestVm{
            Title = p.Title,
            Text = p.Text
        };
        vm = vm.OrderByDescending(p => p.Title.Length);
       
        return View(vm);
    }
    
    
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create([Bind("Title", "Text","Status")] Post post)
    {
    
        if(ModelState.IsValid){
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);
            post.UserId = user.Id;

            post.Created = DateTime.Now;
            _context.Posts.Add(post);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        return View();
    }



    public async Task<IActionResult> Edit(int? id)
    {
        if(id == null){
            return NotFound();
        }
        var post = await _context.Posts.Include(x => x.User).Include(x => x.Comments).ThenInclude(x => x.User).FirstOrDefaultAsync(x => x.PostId == id);
        
        if (post == null){
            return NotFound();
        }

        return View(post);
    }
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int Id, [Bind("PostId,Title,Text,Created,Status")] Post post)
    {
        if(Id != post.PostId)
        {
            return NotFound();
        }
        if(ModelState.IsValid)
        {
            
            post.Created = DateTime.Now;
            _context.Update(post);
            await _context.SaveChangesAsync();
            
        }
        return RedirectToAction("Index");
    }

    

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - cbsStudents</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/cbsStudents.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">CbsStudents</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="administration" asp-action="ListRoles">Admin</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container main-wrapper" >
        <div class="row main-row">
            <div class="col-md-2 sidebar">
                <div class="row">
                    <a class="nav-link text-dark px-2" href="#">Dashboard</a>
                </div>
                <div class="row">
                    <a class="nav-link text-dark px-2" href="#">Public profile</a>
                </div>
                <div class="row">
                   <a class="nav-link text-dark px-2" asp-area="" asp-controller="Event" asp-action="Index">Events</a>
                </div>
                <div class="row">
                   <a class="nav-link text-dark px-2" asp-area="" asp-controller="Posts" asp-action="Index">Posts</a>
                </div>
                <div class="row">
                   <a class="nav-link text-dark px-2" href="#">Collections</a>
                </div>
                <div class="row">
                    <a class="nav-link text-dark px-2" href="#">Chats</a>
                </div>
                <div class="row">
                    <a class="nav-link text-dark px-2" href="#">Volunteers</a>
                </div>
            </div>
            <div class="col-md-10 main-bar">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>

    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - cbsStudents - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer> *@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>