Models/Entities/Event.cs
using cbsStudents.Models.Entities;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;

namespace cbsStudents.Models.Entities;
public class Event
{
    public int EventId { get; set; }

    [Required]
    [Display(Name = "Event Name")]
    [MinLength(3)]
    public string EventName { get; set; }

    [Required]
    [Display(Name ="Description")]
    [MinLength(10)]
    public string Text { get; set; }

    [Required]
    public string Location { get; set; }

    public List<EventComment> Comments { get; set; }

    [Required]
    public DateTime Date { get; set; }

    [Required]
    public PostStatus Status { get; set; }
    
    public string UserId {get; set;}

    public IdentityUser User{get; set;}

}

Controllers/EventCommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CbsStudents.Data;
using System.Security.Claims;


namespace cbsStudents.Controllers
{
    [Authorize]
    public class EventCommentController : Controller
    {
        private readonly CbsStudentsContext _context;

        private readonly UserManager<IdentityUser> _userManager;

        private readonly RoleManager<IdentityRole> _roleManager;

        public EventCommentController(RoleManager<IdentityRole> roleManager,CbsStudentsContext context, UserManager<IdentityUser> userManager)
        {
            this._roleManager = roleManager;
            this._userManager = userManager;
            this._context = context;

        }

        // GET: EventComment
        public async Task<IActionResult> Index()
        {
            var cbsStudentsContext = _context.EventComment.Include(e => e.Event).Include(e => e.User);
            return View(await cbsStudentsContext.ToListAsync());
        }

        [AllowAnonymous]
        // GET: EventComment/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventComment = await _context.EventComment
                .Include(e => e.Event)
                .Include(e => e.User)
                .FirstOrDefaultAsync(m => m.EventCommentId == id);
            if (eventComment == null)
            {
                return NotFound();
            }

            return View(eventComment);
        }

        // GET: EventComment/Create
        
        public IActionResult Create(int id)
        {
            EventComment vm = new EventComment{
                EventId = id,
                UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier)
            };
            // ViewBag.UserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            // ViewBag.EventId = id;

            return View(vm);
        }

        // POST: EventComment/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventCommentId,Text,EventId,UserId")] EventComment eventComment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(eventComment);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details","Event",new {id = eventComment.EventId});            
            }
            ViewData["EventId"] = new SelectList(_context.Event, "EventId", "EventId", eventComment.EventId);
            ViewData["UserId"] = new SelectList(_context.IdentityUserClaim, "Id", "Id", eventComment.UserId);
            return RedirectToAction("Details","Event", new {id = eventComment.EventId}); 
        }

        // GET: EventComment/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventComment = await _context.EventComment.FindAsync(id);
            if (eventComment == null)
            {
                return NotFound();
            }
            ViewData["EventId"] = new SelectList(_context.Event, "EventId", "EventId", eventComment.EventId);
            ViewData["UserId"] = new SelectList(_context.IdentityUserClaim, "Id", "Id", eventComment.UserId);
            return View(eventComment);
        }

        // POST: EventComment/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventCommentId,Text,EventId,UserId")] EventComment eventComment)
        {
            if (id != eventComment.EventCommentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(eventComment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventCommentExists(eventComment.EventCommentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details","Event", new {id = eventComment.EventId});
            }
            ViewData["EventId"] = new SelectList(_context.Event, "EventId", "EventId", eventComment.EventId);
            ViewData["UserId"] = new SelectList(_context.IdentityUserClaim, "Id", "Id", eventComment.UserId);
            return View(eventComment);
        }

        // GET: EventComment/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var eventComment = await _context.EventComment
                .Include(e => e.Event)
                .Include(e => e.User)
                .FirstOrDefaultAsync(m => m.EventCommentId == id);
            if (eventComment == null)
            {
                return NotFound();
            }

            return View(eventComment);
        }

        // POST: EventComment/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var eventComment = await _context.EventComment.FindAsync(id);
            _context.EventComment.Remove(eventComment);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index","Event");
        }

        private bool EventCommentExists(int id)
        {
            return _context.EventComment.Any(e => e.EventCommentId == id);
        }
    }
}

Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CbsStudents.Data;
using cbsStudents.Models.Entities;

namespace cbsStudents.Controllers
{
    [Authorize]
    public class EventController : Controller
    {
        private readonly CbsStudentsContext _context;

        private readonly UserManager<IdentityUser> _userManager;

        private readonly RoleManager<IdentityRole> _roleManager;

        public EventController(RoleManager<IdentityRole> roleManager,CbsStudentsContext context, UserManager<IdentityUser> userManager)
        {
            this._roleManager = roleManager;
            this._userManager = userManager;
            this._context = context;

        }

        [AllowAnonymous]
        // GET: Event
        public IActionResult Index(string SearchString = "")
        {
            if(SearchString == null)
        {
            SearchString = "";
        }
        var events = from e in _context.Event select e;
        events = events.Where(x => x.EventName.Contains(SearchString)).Include(y => y.User);
        
        ViewBag.SearchString = SearchString;
        var vm = new EventIndexVm{Events = events.ToList(), SearchString = SearchString};
        
        return View(vm);
        }

        [AllowAnonymous]
        // GET: Event/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event.Include(x => x.User).Include(x => x.Comments).ThenInclude(x => x.User).FirstOrDefaultAsync(x => x.EventId == id);

            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Event/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Event/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EventId,EventName,Text,Location,Date,Status")] Event @event)
        {
            if (ModelState.IsValid)
            {
                IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);
                @event.UserId = user.Id;
                _context.Add(@event);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // GET: Event/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var @event = await _context.Event.Include(x => x.User).Include(x => x.Comments).ThenInclude(x => x.User).FirstOrDefaultAsync(x => x.EventId == id);

            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }

        // POST: Event/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventId,EventName,Text,Location,Date,Status,UserId")] Event @event)
        {
            if (id != @event.EventId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@event);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.EventId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // GET: Event/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Event/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            IdentityUser user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);
            
            var @event = await _context.Event.FindAsync(id);
            if(user == @event.User || User.IsInRole("Admin")){
                _context.Event.Remove(@event);
                await _context.SaveChangesAsync();
            } else {
                return Problem("You idiot");
            }
            
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
            return _context.Event.Any(e => e.EventId == id);
        }
    }
}

Views/Event/Create.cshtml
@model Event

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            @await Html.PartialAsync("_PartialEvent", Model)  
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Event/Delete.cshtml
@model Event

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    @await Html.PartialAsync("_PartialDeleteDetails", Model) 
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EventId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <button asp-action="Index" class="btn btn-primary">Back</button>
    </form>
</div>

Views/Event/Details.cshtml
@model Event

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Event</h4>
    <hr />
    @await Html.PartialAsync("_PartialDeleteDetails", Model) 
</div>

<div class="row">
    @* <div class="col-sm-1">
        <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model?.EventId">Edit</a>
    </div> | *@
    <div class="col-sm-1">
        <a asp-action="Index" class="btn btn-primary">Back</a>
    </div>
</div>

<br>


<div class="row d-flex justify-content-center">
    <div class="col-md-8 col-lg-6">
        <div class="card shadow-0 border" style="background-color: #f0f2f5;">
            @if (SignInManager.IsSignedIn(User))
            {
            <div class="row">
                <div class="col-sm-2">
                    <a class="text-white btn btn-primary" asp-area="" asp-route-id="@Model.EventId" asp-controller="EventComment" asp-action="Create">
                        Comment
                    </a>
                </div>
            </div>
            }
            <div class="card-body p-4">
                @foreach (var comment in Model.Comments)
                {      
                <div class="card mb-4">
                    <div class="card-body">
                        <p>@comment.Text</p>
                        <div class="d-flex justify-content-between">
                            <div class="d-flex flex-row align-items-center">
                                <p class="small mb-0 ms-2">@comment.User</p>
                            </div>
                            @if (SignInManager.IsSignedIn(User))
                            {
                                @if (UserManager.GetUserId(User).Equals(comment.UserId) || User.IsInRole("Admin") || UserManager.GetUserId(User).Equals(Model.UserId))
                                {
                                    <a asp-controller="EventComment" asp-action="Edit" asp-route-id="@comment.EventCommentId" class="btn btn-primary">Edit</a>
                                    <a asp-controller="EventComment" asp-action="Details" asp-route-id="@comment.EventCommentId" class="btn btn-primary">Details</a> 
                                    <a asp-controller="EventComment" asp-action="Delete" asp-route-id="@comment.EventCommentId" class="btn btn-danger">Delete</a>
                                } else {
                                    <a asp-controller="EventComment" asp-action="Details" asp-route-id="@comment.EventCommentId" class="btn btn-primary">Details</a>                                     
                                }
                            } else {
                                <a asp-controller="EventComment" asp-action="Details" asp-route-id="@comment.EventCommentId" class="btn btn-primary">Details</a> 
                            }
                        </div>
                    </div>
                </div>
                }
            </div>
        </div>
    </div>
</div>

Views/Event/Edit.cshtml
@model Event

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{
    ViewData["Title"] = "Edit";
    ViewBag.EventId = Model.EventId;
    
}

<h1>Edit</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            @await Html.PartialAsync("_PartialEvent", Model)  
            <input type="hidden" asp-for="EventId"/>
        </form>
    </div>
</div>

@* 
Make it possible for a user to post a comment on this event
 *@
<br>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Event/Index.cshtml
@model EventIndexVm

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{
    ViewData["Title"] = "Index";
}

<h1>Events</h1>

@if (SignInManager.IsSignedIn(User))
{
<p>
    <a asp-action="Create" class="btn btn-primary">Create New</a>
</p>
    
}

<div class="container">
    <form asp-controller="Event" asp-action="Index">
        <p>
            Event name: <input type="text" name="SearchString" value = "@ViewBag.SearchString"/>
            <input type="submit" value="Filter" />
        </p>
    </form>
    <div class="row">
@foreach (var item in Model.Events)
{
    <div class="col-lg-4 mb-4">
        <div class="card card-styling">
            <div class="card-body">
                <h5 class="card-title">@Html.DisplayFor(modelItem => item.EventName)</h5>
                <p class="card-text">@Html.DisplayFor(modelItem => item.Text) </p>
                @if (SignInManager.IsSignedIn(User))
                {
                    @if (UserManager.GetUserId(User).Equals(item.UserId) || User.IsInRole("Admin"))
                    {
                        <a asp-action="Edit" asp-route-id="@item.EventId" class="btn btn-primary">Edit</a>
                        <a asp-action="Details" asp-route-id="@item.EventId" class="btn btn-primary">Details</a> 
                        <a asp-action="Delete" asp-route-id="@item.EventId" class="btn btn-danger">Delete</a>
                    }
                    else
                    {
                        <a asp-action="Details" asp-route-id="@item.EventId" class="btn btn-primary">Details</a> 
                    }   
                } else {
                    <a asp-action="Details" asp-route-id="@item.EventId" class="btn btn-primary">Details</a> 
                }
            </div>
        </div>
    </div>

    
}
    </div>
</div>

Views/Event/_PartialDeleteDetails.cshtml
@model Event

<dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EventName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EventName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Text)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Text)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            Creator
            @Html.DisplayNameFor(model => model.User.Email):
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Email)
        </dd>
    </dl>

Views/Event/_PartialEvent.cshtml
@model Event

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="EventName" class="control-label"></label>
            <input asp-for="EventName" class="form-control" />
            <span asp-validation-for="EventName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Text" class="control-label"></label>
            <input asp-for="Text" class="form-control" />
            <span asp-validation-for="Text" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Location" class="control-label"></label>
            <input asp-for="Location" class="form-control" />
            <span asp-validation-for="Location" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Date" class="control-label"></label>
            <input asp-for="Date" class="form-control" />
            <span asp-validation-for="Date" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Status" class="control-label"></label>
            <select asp-for="Status" class ="form-control" asp-items="@Html.GetEnumSelectList<PostStatus>()">
                @* <option value="Draft">DRAFT</option>
                <option value="Published">PUBLISHED</option> *@
            </select>
        </div>
        <input type="hidden" asp-for="UserId"/>
        <div class="row">
            <div class="col-sm-3">
                <input type="submit" class="btn btn-primary" value="Save"/>
            </div> |
            <div class="col-sm-3">
                <button asp-action="Index" class="btn btn-primary">Cancel</button>
            </div>
        </div>

            